# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # `container-job` で実行するサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使用されるラベル
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: example
          POSTGRES_USER: example
          POSTGRES_PASSWORD: example
          POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
        # postgres が起動するまで待機するようにヘルスチェックを設定する
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: exec create_tables.sql
      run: |
        cat ./schema/ddl/create_table.sql | PGPASSWORD=example psql -f -hpostgres -p5432 -Uexample example
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -B clean test
